### PR TITLE
Ability to create .env where there is none

### PR DESCRIPTION
**Pull request by mikz**
Includes #1

Makes the code more DRY, uses proper escaping primitives and does not crash on missing .env file.

### CODE REVIEW

**Comment by adis-io** [comment]
:+1:

**Comment by vala** [comment]
Hi @mikz glad the gem's useful to you, and thanks for the PR, I'll review it as soon as I can

**Comment by mikz** [comment]
@vala great, it probably needs a documentation update to describe the setup.

Adding .env to linked files and adding the dotenv:touch before check linked files.

Please let me know if there is anything I can do. Did first deploy with it on friday and all worked.

**Comment by vala** [comment]
Hi @mikz 

Sorry taking so much time looking into your PR.
Globally the PR is great, and I appreciate the changes, even in the coding style.

Just two things :
- Did the `fetch(:capistrano_dotenv_path)` worked for you ? I had to force the path to be a string (with `{ shared_path.join('.env').to_s }` or `fetch(:capistrano_dotenv_path).to_s.shellescape`) since the config returns a `Pathname` and that `shellescape` is not defined for `Pathname`.
- How are you supposed to unserialize the shellescaped env vars ? If I set a config with : `cap staging config:set FOO="bar baz"` then when I try to `puts ENV['FOO']` I get `# => bar\ baz` and not `bar baz` as expected. This seems not to be the right thing to do, since this gem should not affect the way `dotenv` is used from the app

**Comment by adis-io** [comment]
+1, I stumbled with this issue. It's not unserialize after deploy is done.

**Comment by mikz** [comment]
@vala you are right in both cases.

We do have a monkey patch in our deploy scripts to serialize Pathname automatically.

Also you are right with the .shellescape on the variables, as that would be needed only when they are passed to the command line.

Will fix those and try to add a test!

**Comment by mikz** [comment]
@vala updated, and added a spec for the double quoting issue

**Comment by vala** [comment]
Hey @mikz thanks for the update, and starting to add tests.
But when I read your tests, if I send `cap staging config:set FOO="bar baz"`, then I'll get `FOO=bar baz` in my `.env` file. Will `dotenv` properly parse the string so that `puts ENV['FOO']` returns `bar baz` and not just `bar` ?

**Comment by mikz** [comment]
@vala yep

``` ruby
[1] pry(main)> File.read('.env')
=> "FOO=bar bar val\n"
[2] pry(main)> ENV['FOO']
=> "bar bar val"
```

**Comment by vala** [comment]
Merged ! Thanks

**Pull request merged**
